#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo  "Running Eslint"
echo "..."
npm run lint
echo "Lint succeeded\n\n"

echo "Linting staged files"
echo "..."
npx lint-staged --allow-empty 
echo "Staged files are ok\n\n"

echo "Running tests"
echo "..."
npm test
echo "Tests succeeded\n"