#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo  "Running Eslint\n"
npm run lint
echo "Lint succeeded\n"

echo "..."

echo "Linting staged files\n"
npx lint-staged && git add .
echo "Staged files are ok"

echo "..."

echo "Running tests"
npm test
echo "Tests succeeded"